version: '3.8'

services:
  model:
    container_name: semantic_train
    build:
      context: ..
      dockerfile: docker/Dockerfile.model
    volumes:
      - ../scripts/model:/app/model
      - ../data:/app/data
    command: sleep infinity  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
