version: '3.8'

services:
  data_prep:
    build:
      context: ..
      dockerfile: docker/Dockerfile.data_prep
    volumes:
      - ../src/data_preparation:/app/data_prep
      - ../outputs:/app/outputs
      - ../data:/app/data
    command: sleep infinity  # Mantiene el contenedor abierto para ejecutar scripts manualmente
