# Dockerfile.model
FROM nvcr.io/nvidia/pytorch:24.02-py3

WORKDIR /app

# Copy dependencies and install them
COPY requirements/requirements_model.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Keep the container open for manual script execution
CMD ["/bin/bash"]
